In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5,5)

In [5]:
layer.weight.data

tensor([[ 0.4014, -0.2631,  0.1755,  0.2201, -0.1091],
        [ 0.0365,  0.0907,  0.3039, -0.1519,  0.2725],
        [-0.2982, -0.0479,  0.4396,  0.1407,  0.4285],
        [-0.2137,  0.3008,  0.0673,  0.2893,  0.1470],
        [ 0.3842,  0.1994, -0.4411,  0.0845,  0.3375]])

In [7]:
nn.init.uniform_(layer.weight, a=0.0, b=1.3)

Parameter containing:
tensor([[0.8787, 0.0590, 1.2545, 0.4598, 0.7551],
        [0.5645, 0.7739, 0.7495, 0.2491, 0.6871],
        [0.8417, 0.6605, 0.2484, 0.6737, 0.5075],
        [0.0116, 0.6777, 1.1313, 0.6135, 0.6654],
        [1.1058, 0.4026, 0.5175, 0.3260, 0.0959]], requires_grad=True)

In [11]:
nn.init.normal_(layer.weight, mean=0.0, std=1.0)

Parameter containing:
tensor([[-0.4099,  0.1997, -0.3503,  0.5226, -1.3953],
        [-0.4543,  1.0482, -0.6946, -2.1051,  0.4805],
        [ 1.0449,  0.3153,  0.1907,  1.5930,  0.0529],
        [ 2.5886, -1.3979, -1.3223,  0.4418, -1.8336],
        [-0.3217, -1.6067,  0.5944, -0.5928, -1.3172]], requires_grad=True)

In [13]:
nn.init.constant_(layer.bias, 0)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [14]:
nn.init.ones_(layer.bias)

Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [15]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [16]:
nn.init.xavier_uniform_(layer.weight, gain=1.0)

Parameter containing:
tensor([[-0.4247, -0.1438,  0.5587, -0.7364,  0.2277],
        [-0.5815, -0.4457, -0.7366, -0.1258, -0.3328],
        [-0.7072,  0.2169, -0.6119,  0.4261,  0.0203],
        [ 0.1062,  0.3324, -0.6773, -0.0059, -0.6268],
        [-0.1276,  0.1201,  0.6985,  0.3811,  0.4831]], requires_grad=True)

In [17]:
nn.init.xavier_normal_(layer.weight, gain=1.0)

Parameter containing:
tensor([[ 0.6682,  0.9350, -0.3685,  0.3655, -0.0594],
        [ 0.6702, -0.1294,  0.4250, -0.5296,  0.1994],
        [-0.1152, -0.2993,  0.3821, -0.3204,  0.3553],
        [-0.3106,  0.6611,  0.1649, -0.2478, -0.1657],
        [ 0.0941,  0.2504, -0.9476,  0.0281,  0.3592]], requires_grad=True)